source 'https://rubygems.org'

group :test do
  gem 'puppet',              '~> 7.0'
  gem 'rspec',               '~> 3.12'
  gem 'rspec-puppet',        '~> 5.0'
  gem 'rspec-puppet-facts',  '~> 4.0'
  gem 'puppetlabs_spec_helper'
end
